-- Fusion Beef - Database Seed
-- 46 produtos + 0 configurações
-- Gerado em: 2025-12-08T18:50:03.973Z

-- Limpar dados existentes
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE products;
TRUNCATE TABLE settings;
TRUNCATE TABLE scrape_logs;
SET FOREIGN_KEY_CHECKS = 1;

-- Produtos
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('500100318', 'Racas Britanicas Paleta Shoulder Brasil Cabaña Las Lilas Grass Fed Resfriado', 'Bovinos Premium', '66.99', '107.18', '60', 'https://meuminerva.com/media/catalog/product/5/0/500100318.jpg', '/images/products/500100318.jpg', 'RESFRIADO', 'https://meuminerva.com/racas-britanicas-paleta-shoulder-brasil-cabana-las-lilas-grass-fed-resfriado-500100318.html', 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('200004423', 'Angus Maminha Uruguay Cabaña Las Lilas Grass Fed Resfriado', 'Bovinos Premium', '67.99', '108.78', '60', 'https://meuminerva.com/media/catalog/product/2/0/200004423.jpg', '/images/products/200004423.jpg', 'RESFRIADO', 'https://meuminerva.com/angus-maminha-uruguay-cabana-las-lilas-grass-fed-resfriado-200004423.html', 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('500100446', 'Novilho Fralda Brasil Cabaña Las Lilas Grain Fed Resfriado', 'Bovinos Premium', '56.99', '91.18', '60', 'https://meuminerva.com/media/catalog/product/5/0/500100446.jpg', '/images/products/500100446.jpg', 'in_stock', 'https://meuminerva.com/novilho-fralda-brasil-cabana-las-lilas-grass-fed-resfriado-500100446.html', 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('500100432', 'Novilho Ancho Brasil Cabaña Las Lilas Grain Fed Resfriado', 'Bovinos Premium', '79.99', '127.98', '60', 'https://meuminerva.com/media/catalog/product/5/0/500100432.jpg', '/images/products/500100432.jpg', 'in_stock', 'https://meuminerva.com/novilho-ancho-brasil-cabana-las-lilas-grass-fed-resfriado-500100432.html', 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('500100445', 'Novilho Fralda Red Brasil Cabaña Las Lilas Grass Fed Resfriado', 'Bovinos Premium', '78.98', '126.37', '60', 'https://meuminerva.com/media/catalog/product/5/0/500100445.jpg', '/images/products/500100445.jpg', 'RESFRIADO', 'https://meuminerva.com/novilho-fralda-red-brasil-cabana-las-lilas-grass-fed-resfriado-500100445.html', 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('500100435', 'Novilho Paleta Coração Brasil Cabaña Las Lilas Grass Fed Resfriado', 'Bovinos Premium', '54.98', '87.97', '60', 'https://meuminerva.com/media/catalog/product/5/0/500100435.jpg', '/images/products/500100435.jpg', 'RESFRIADO', 'https://meuminerva.com/novilho-paleta-coracao-brasil-cabana-las-lilas-grass-fed-resfriado-500100435.html', 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('500100423', 'Novilho Picanha Leve Brasil Cabaña Las Lilas Grain Fed Resfriado', 'Bovinos Premium', '114.99', '183.98', '60', 'https://meuminerva.com/media/catalog/product/5/0/500100423.jpg', '/images/products/500100423.jpg', 'in_stock', 'https://meuminerva.com/novilho-picanha-leve-brasil-cabana-las-lilas-grain-fed-resfriado-500100423.html', 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('500100437', 'Novilho Acem Brasil Cabaña Las Lilas Grass Fed Resfriado', 'Bovinos Premium', '51.98', '83.17', '60', 'https://meuminerva.com/media/catalog/product/5/0/500100437.jpg', '/images/products/500100437.jpg', 'RESFRIADO', 'https://meuminerva.com/novilho-acem-brasil-cabana-las-lilas-grass-fed-resfriado-500100437.html', 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('500100273', 'Novilho File Mignon Sem Cordão Brasil Cabaña Las Lilas Grass Fed Resfriado', 'Bovinos Premium', '76.99', '123.18', '60', 'https://meuminerva.com/media/catalog/product/5/0/500100273.jpg', '/images/products/500100273.jpg', 'in_stock', 'https://meuminerva.com/novilho-file-mignon-brasil-cabana-las-lilas-grass-fed-resfriado-500100273.html', 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('500100282', 'Novilho Fralda Red Brasil Cabaña Las Lilas Grass Fed Resfriado', 'Bovinos Premium', '61.99', '99.18', '60', 'https://meuminerva.com/media/catalog/product/5/0/500100282.jpg', '/images/products/500100282.jpg', 'RESFRIADO', 'https://meuminerva.com/novilho-fralda-red-brasil-cabana-las-lilas-grass-fed-resfriado-500100282.html', 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('500100265', 'Novilho Chorizo Brasil Cabaña Las Lilas Grass Fed Resfriado', 'Bovinos Premium', '49.99', '79.98', '60', 'https://meuminerva.com/media/catalog/product/5/0/500100265.jpg', '/images/products/500100265.jpg', 'RESFRIADO', 'https://meuminerva.com/novilho-chorizo-brasil-cabana-las-lilas-grass-fed-resfriado-500100265.html', 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('500100281', 'Novilho Fralda Brasil Cabaña Las Lilas Grass Fed Resfriado', 'Bovinos Premium', '46.99', '75.18', '60', 'https://meuminerva.com/media/catalog/product/5/0/500100281.jpg', '/images/products/500100281.jpg', 'in_stock', 'https://meuminerva.com/novilho-fralda-brasil-cabana-las-lilas-grass-fed-resfriado-500100281.html', 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('500001512', 'Picanha Pul (bife) Resfriado', 'Bovinos', '47.49', '75.98', '60.0', NULL, NULL, 'in_stock', 'https://sul.meuminerva.com/bovinos-sul.html', 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('500000332', 'Musculo Traseiro Pul Resfriado', 'Bovinos', '28.19', '45.10', '60.0', NULL, NULL, 'in_stock', 'https://sul.meuminerva.com/bovinos-sul.html', 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('500000051', 'Contra File Pul Pro Resfriado', 'Bovinos', '46.99', '75.18', '60.0', NULL, NULL, 'in_stock', 'https://sul.meuminerva.com/bovinos-sul.html', 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('500000251', 'Patinho Pul Resfriado', 'Bovinos', '37.99', '60.78', '60.0', NULL, NULL, 'in_stock', 'https://sul.meuminerva.com/bovinos-sul.html', 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('500000301', 'Lagarto Pul Resfriado', 'Bovinos', '34.99', '55.98', '60.0', NULL, NULL, 'in_stock', 'https://sul.meuminerva.com/bovinos-sul.html', 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('500086540', 'Maminha Da Alcatra Pul Selection Congelado', 'Bovinos', '39.49', '63.18', '60.0', NULL, NULL, 'in_stock', 'https://sul.meuminerva.com/bovinos-sul.html', 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('500000024', 'File Mignon S/ Cordão Pul Selection Resfriado', 'Bovinos', '85.99', '137.58', '60.0', NULL, NULL, 'in_stock', 'https://sul.meuminerva.com/bovinos-sul.html', 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('77483', 'Barriga Suína Brasil Congelado', 'Suínos', '23.99', '38.38', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/b/a/barriga_suina_brasil_congelado_-_77483.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('83667', 'Costela Suína Temperada Brasil Generico Congelada', 'Suínos', '23.79', '38.06', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/c/o/costela_suina_temperada_brasil_generico_congelada_-_83667.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('77189', 'Sobrepaleta Suína S/ Osso Brasil Generico Congelado', 'Suínos', '20.59', '32.94', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/s/o/sobrepaleta_suina_s__osso_brasil_generico_congelado_-_77189.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('77175', 'Costela Suína Brasil Generico Congelado', 'Suínos', '21.19', '33.90', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/c/o/costela_suina_brasil_generico_congelado_-_77175.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('77124', 'Pernil Suíno S/ Pele C/ Osso Brasil Generico Congelado', 'Suínos', '17.29', '27.66', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/p/e/pernil_suino_s__pele_c__osso_brasil_generico_congelado_-_77124.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('77126', 'Pernil Suíno S/ Pele S/ Osso Brasil Generico Congelado', 'Suínos', '20.79', '33.26', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/p/e/pernil_suino_s__pele_s__osso_brasil_generico_congelado_-_77126.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('77138', 'Pernil Suino C/p C/o Brasil Generico Congelado', 'Suínos', '16.49', '26.38', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/p/e/pernil_suino_c_p_c_o_brasil_generico_congelado_-_77138.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('77171', 'Barriga Suína Brasil Generico Congelado', 'Suínos', '23.99', '38.38', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/b/a/barriga_suina_brasil_generico_congelado_-_77171.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('500101554', 'Salmao Chile Salar Porcionado Granel Cx 6kg', 'Pescados', '83.83', '134.13', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/s/a/salmao_chile_salar_porcionado_granel_cx_6kg_-_500101554.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('58788', 'Bolinho Bacalhau Portugal Riberalves 12x300g Congelado', 'Pescados', '62.62', '100.19', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/b/o/bolinho_bacalhau_portugal_riberalves_12x300g_congelado_-_58788.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('57105', 'Panga Interfolhado Não Aparado Vietnam Pul Congelado', 'Pescados', '20.19', '32.30', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/p/a/panga_interfolhado_nao_aparado_vietnam_pul_congelado_-_57105.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('45515', 'Panga Interfolhado Standard Vietnam Pul Congelado', 'Pescados', '22.72', '36.35', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/p/a/panga_interfolhado_standard_vietnam_pul_congelado_-_45515.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('3952', 'Tilapia Foodservice Granel Brasil Pul Congelado', 'Pescados', '38.37', '61.39', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/t/i/tilapia_foodservice_granel_brasil_pul_congelado_-_3952.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('3375', 'Merluza Argentina Pul 600g Congelado', 'Pescados', '29.79', '47.66', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/m/e/merluza_argentina_pul_600g_congelado_-_3375.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('3954', 'Salmão Chile Pul 1/3 Lbs Congelado', 'Pescados', '76.76', '122.82', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/s/a/salmao_chile_pul_1_3_lbs_congelado_-_3954.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('3535', 'Panga Pacote Varejo Vietnã Pul 600g Congelado', 'Pescados', '27.26', '43.62', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/p/a/panga_pacote_varejo_vietna_pul_600g_congelado_-_3535.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('800000524', 'Carre Francês Chile Patagonia Congelado', 'Cordeiros', '185.85', '297.36', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/c/a/carre_frances_chile_patagonia_congelado_-_800000524.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('6664', 'Carre 13 Ripas Estância 92 Uruguai Congelado', 'Cordeiros', '130.29', '208.46', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/c/a/carre_13_ripas_estancia_92_uruguai_congelado_-_6664.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('22058', 'T-bone De Cordeiro Uruguai Estância 92 Congelado', 'Cordeiros', '51.51', '82.42', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/t/-/t-bone_de_cordeiro_uruguai_estancia_92_congelado_-_22058.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('21975', 'File De Panga Empanado Brasil Baita 700g Congelado', 'Empanados', '35.34', '56.54', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/f/i/file_de_panga_empanado_brasil_baita_700g_congelado_-_21975.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('68510', 'Filezinho Empanado De Frango 700g Brasil Baita Congelado', 'Empanados', '28.27', '45.23', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/f/i/filezinho_empanado_de_frango_700g_brasil_baita_congelado_-_68510.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('68467', 'Chicken Empanado De Frango 700g Brasil Baita Congelado', 'Empanados', '18.88', '30.21', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/c/h/chicken_empanado_de_frango_700g_brasil_baita_congelado_-_68467.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('68465', 'Chicken Empanado De Frango 1,5kg Brasil Baita Congelado', 'Empanados', '18.98', '30.37', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/c/h/chicken_empanado_de_frango_1_5kg_brasil_baita_congelado_-_68465.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('68490', 'Filezinho Empanado De Frango 1,5kg Baita Congelado', 'Empanados', '27.26', '43.62', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/f/i/filezinho_empanado_de_frango_1_5kg_baita_congelado_-_68490.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('21789', 'Jerked Beef Dianteiro Foodservice Brasil 5kg Pul Resfriado', 'Jerked Beef', '38.39', '61.42', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/j/e/jerked_beef_dianteiro_foodservice_brasil_5_kg_pul_resfriado_-_21789.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('82964', 'Jerked Beef Dianteiro 400g Brasil Pul Resfriado', 'Jerked Beef', '39.99', '63.98', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/j/e/jerked_beef_dianteiro_400g_brasil_pul_resfriado_-_82964.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
INSERT INTO products (sku, name, category, priceOriginal, priceWithMarkup, markup, imageUrl, imageLocalPath, stockStatus, minervaUrl, inStock, createdAt, updatedAt) VALUES ('86975', 'Azeite De Oliva Extra Virgem Português Alma Lusa Vidro', 'Azeite', '50.00', '80.00', '60.00', 'https://meuminerva.com/media/catalog/product/cache/1/small_image/200x/9df78eab33525d08d6e5fb8d27136e95/a/z/azeite_de_oliva_extra_virgem_portugues_alma_lusa_vidro_-_86975.jpg', NULL, NULL, NULL, 1, NOW(), NOW());
